### ISSUE TITLE
The core functionality appears to be already included in Symphony 2.4 upload field

### ISSUE THREAD

**Issue by tmslnz** [michael-e/uniqueuploadfield#13]
Hi, just a heads up: I believe this functionality is now part of Symphony 2.4. It would be good to have this mentioned in the README / repo description to warn people that the extension is not needed in versions >= 2.4

**Comment by tmslnz** [comment]
Merry Christmas :)

**Comment by michael-e** [comment]
Merry Christmas! :-))

**Comment by DavidOliver** [comment]
Und frohes neues Jahr.

**Comment by michael-e** [comment]
Dankeschön!

**Comment by DavidOliver** [comment]
@michael-e, I just tried uploading a file with a non-unique filename using the core upload field and it was saved with a `_1` on the end.

**Comment by michael-e** [comment]
Have you removed the old file before? AFAIK, the core upload field does this only when the old file has not been removed explicitely (i.e. you are doing two steps in one).

**Comment by DavidOliver** [comment]
When uploading a file with entry A which has the same filename as a file already uploaded with entry B, we end up with both files intact, with entry A's having `_1` appended before the file extension. This is the case whether or not entry A is saved after removing its previous file and before uploading its new file.

So it seems file loss and subsequent downloading of the wrong stuff is at least avoided with the core upload field, even if users upload multiple (potentially different) files with the same name.

**Comment by michael-e** [comment]
I mean s.th. different. If you take just one entry, and you upload a file which has been removed before (for this entry), do you get a new filename then?

**Comment by DavidOliver** [comment]
No, but in that case the old file has already been deleted from disk.

**Comment by michael-e** [comment]
So you are still in trouble, because browsers will have cached versions of your file (depending on the cache headers of your files, of course), This is the problem my extension tries to solve. By appending a unique timestamp value there is no caching issue.

**Comment by DavidOliver** [comment]
Good point. :)

**Comment by michael-e** [comment]
This means that you can use "far-future expire" headers without worries. :-)

**Comment by DavidOliver** [comment]
Yes. [I should have](http://symphonyextensions.com/extensions/page_http_caching/) had those in mind!

**Comment by michael-e** [comment]
:-))
