### ISSUE TITLE
Marking compatibility with Sym 2.x/2.6

### ISSUE THREAD

**Issue by DavidOliver** [michael-e/uniqueuploadfield#14]
(Because I haven't been making enough noise already today.)

This is working fine for me in 2.6. [I think](https://github.com/symphonists/symphony-extensions-network/issues/4#issuecomment-191789871) extensions should now be marked with a `max` of `2.x.x`.

**Comment by michael-e** [comment]
Will do, for all my extensions, as soon as I find the time!

**Comment by michael-e** [comment]
Done in be5ae838b9130005aae7d270ab3e9cb0fa354153
